const skillsData = [
  { id: 1, name: "Programista", iconClass: "fa-solid fa-computer-classic" },
  { id: 2, name: "Artysta", iconClass: "fa-solid fa-pen" },
  { id: 3, name: "Piekarz", iconClass: "fa-solid fa-pie" },
  { id: 4, name: "Gracz", iconClass: "fa-solid fa-gamepad" },
  { id: 5, name: "Czytelnik", iconClass: "fa-solid fa-book-open-cover" },
  { id: 6, name: "Pianista", iconClass: "fa-solid fa-piano-keyboard" },
  { id: 7, name: "Architekt", iconClass: "fa-solid fa-archway" },
  { id: 8, name: "Fotograf", iconClass: "fa-solid fa-camera-retro" },
  { id: 9, name: "Grafik", iconClass: "fa-solid fa-image" },
  { id: 10, name: "Budowlaniec", iconClass: "fa-solid fa-trowel-bricks" },
  { id: 11, name: "Fryzjer", iconClass: "fa-solid fa-user-hair" },
  { id: 12, name: "Sportowiec", iconClass: "fa-solid fa-futbol" },
  { id: 13, name: "Serialowiec", iconClass: "fa-solid fa-tv-retro" },
  { id: 14, name: "Rośliniarz", iconClass: "fa-sharp fa-regular fa-seedling" },
  { id: 15, name: "Pisarz", iconClass: "fa-regular fa-pen" },
  { id: 16, name: "Rybiarz", iconClass: "fa-solid fa-fish" },
  { id: 17, name: "Plywacz", iconClass: "fa-solid fa-person-swimming" },
  { id: 18, name: "Podróżnik", iconClass: "fa-solid fa-plane" },
  { id: 19, name: "Zakupoholik", iconClass: "fa-solid fa-bag-shopping" },
  { id: 20, name: "Rowerowiarz", iconClass: "fa-regular fa-bicycle" },
  { id: 21, name: "Astronom", iconClass: "fa-solid fa-stars" },
  { id: 22, name: "Szachista", iconClass: "fa-solid fa-chess" },
];

export default skillsData;
